### ISSUE TITLE
BUGGGZ

### ISSUE THREAD

**Issue by codeofsumit** [felixheck/wc2018-slack-bot#4]
Postet nix mehr. Logs hier:

```
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
06/16 01:19 PM (2d)
    at <anonymous>
06/16 01:19 PM (2d)
    at getGames (/home/nowuser/src/index.js:46:6)
06/16 01:19 PM (2d)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
06/16 01:19 PM (2d)
(node:84) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
06/16 01:19 PM (2d)
    at process._tickCallback (internal/process/next_tick.js:188:7)
06/17 03:54 PM (1d)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
06/17 03:54 PM (1d)
    at getGames (/home/nowuser/src/index.js:46:6)
06/17 03:54 PM (1d)
    at <anonymous>
06/17 03:54 PM (1d)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 93)
06/17 03:54 PM (1d)
    at process._tickCallback (internal/process/next_tick.js:188:7)
06/17 10:12 PM (18h)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
06/17 10:12 PM (18h)
    at getGames (/home/nowuser/src/index.js:46:6)
06/17 10:12 PM (18h)
    at process._tickCallback (internal/process/next_tick.js:188:7)
06/17 10:12 PM (18h)
    at <anonymous>
06/17 10:12 PM (18h)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 311)
06/18 12:17 AM (16h)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
06/18 12:17 AM (16h)
    at process._tickCallback (internal/process/next_tick.js:188:7)
06/18 12:17 AM (16h)
    at getGames (/home/nowuser/src/index.js:46:6)
06/18 12:17 AM (16h)
    at <anonymous>
06/18 12:17 AM (16h)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 312)
06/18 02:58 AM (13h)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
06/18 02:58 AM (13h)
    at getGames (/home/nowuser/src/index.js:46:6)
06/18 02:58 AM (13h)
    at <anonymous>
06/18 02:58 AM (13h)
    at process._tickCallback (internal/process/next_tick.js:188:7)
06/18 02:58 AM (13h)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 315)
06/18 05:19 AM (11h)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
06/18 05:19 AM (11h)
    at <anonymous>
06/18 05:19 AM (11h)
    at process._tickCallback (internal/process/next_tick.js:188:7)
06/18 05:19 AM (11h)
    at getGames (/home/nowuser/src/index.js:46:6)
06/18 05:19 AM (11h)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 317)
06/18 08:24 AM (8h)
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
06/18 08:24 AM (8h)
    at process._tickCallback (internal/process/next_tick.js:188:7)
06/18 08:24 AM (8h)
    at <anonymous>
06/18 08:24 AM (8h)
    at getGames (/home/nowuser/src/index.js:46:6)
06/18 08:24 AM (8h)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 319)
```

**Comment by felixheck** [comment]
thanks for reporting.
